# Generated by Django 5.0.6 on 2024-05-27 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FindOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find_out_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('father_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('mobile_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Мобильный телефон')),
                ('iin', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИИН')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Дата рождения')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('find_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.findout', verbose_name='Как узнал')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.gender', verbose_name='Пол')),
            ],
        ),
    ]
