# Generated by Django 5.0.6 on 2024-05-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='findout',
            options={'verbose_name': 'Как узнал', 'verbose_name_plural': 'Как узнали'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'Пол', 'verbose_name_plural': 'Пол'},
        ),
    ]
