# Generated by Django 5.0.6 on 2024-05-28 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_alter_client_options_alter_findout_options_and_more'),
        ('doctors', '0002_alter_assistant_options_alter_doctorclient_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChairNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Номер кабинета',
                'verbose_name_plural': 'Номера кобинет',
            },
        ),
        migrations.CreateModel(
            name='PaymentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Состояние оплаты',
                'verbose_name_plural': 'Состояния оплат',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тип оплаты',
                'verbose_name_plural': 'Типы оплат',
            },
        ),
        migrations.CreateModel(
            name='RecordingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тип записи',
                'verbose_name_plural': 'Типы записей',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(verbose_name='Дата приема')),
                ('record_start', models.DateField(verbose_name='Время начало')),
                ('record_end', models.DateField(verbose_name='Время окончания')),
                ('title', models.CharField(max_length=255)),
                ('notes', models.IntegerField()),
                ('reason', models.IntegerField()),
                ('reception_day', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.assistant')),
                ('chair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.chairnum', verbose_name='Номер кабинета')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctors')),
                ('payment_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.paymentstate', verbose_name='Состояние оплаты')),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.paymenttype', verbose_name='Тип оплаты')),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.service')),
                ('recording_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.recordingtype', verbose_name='Тип записи')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
