# Generated by Django 5.0.6 on 2024-05-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistant',
            options={'verbose_name': 'Ассистент', 'verbose_name_plural': 'Ассистенты'},
        ),
        migrations.AlterModelOptions(
            name='doctorclient',
            options={'verbose_name': 'Врач-Клиент', 'verbose_name_plural': 'Врачи-Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name': 'Врач', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
    ]
